### ISSUE TITLE
`vagrant up` fails

### ISSUE THREAD

**Issue by denpatin** [pltanton/metable#1]
Executing `vagrant up` fails immediately with the following:

![screen shot 2017-01-21 at 1 07 28 pm](https://cloud.githubusercontent.com/assets/1271040/22173640/9c88d1ac-dfda-11e6-8fb0-a4ce6b84e03c.png)

> I've tried this `vagrant login` command and got successfully authenticated, however the error remained the same.

**Comment by pltanton** [comment]
I'm sorry, this is your **roscomnadzor** problem, use vpn or proxy to download box :rage4:

**Comment by denpatin** [comment]
Btw, just FYI. The problem is in the built-in `curl` and not due to proxy, so executing `sudo rm /opt/vagrant/embedded/bin/curl` makes everything here working.

**Comment by pltanton** [comment]
OSX problems?

**Comment by denpatin** [comment]
It appeared on Windows as well. Still sometimes this problem occurs, sometimes not. Seems like the reason's hidden in a certain set of Vagrant versions.

**Comment by pltanton** [comment]
You can open an issue in vagrant's bug tracker.

**Comment by denpatin** [comment]
Already opened long ago :)

To say more, running `vagrant up` here still produces an error at the end. There might be something in the installation script. The end of `up`ping the image:

```
==> default: downloading pciutils-3.5.4-1-x86_64.pkg.tar.xz...
==> default: downloading xfsprogs-4.10.0-1-x86_64.pkg.tar.xz...
==> default: downloading virtualbox-guest-modules-arch-5.1.18-1-x86_64.pkg.tar.xz...
==> default: downloading virtualbox-guest-utils-nox-5.1.18-1-x86_64.pkg.tar.xz...
==> default: checking keyring...
==> default: checking package integrity...
==> default: loading package files...
==> default: checking for file conflicts...
==> default: error:
==> default: failed to commit transaction (conflicting files)
==> default: ca-certificates-utils: /etc/ssl/certs/ca-certificates.crt exists in filesystem
==> default: Errors occurred, no packages were upgraded.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by pltanton** [comment]
It is realited to box's provisioning script
